INSERT INTO warehouse_items (warehouse_id, item_id, volume, created, updated) VALUES 
(1, 1, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
(1, 2, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 3, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 4, 1,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 5, 1,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 6, 1100,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 7, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 8, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 9, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 10, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 11, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 12, 1000,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
(1, 13, 1,  CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());